
###############################################################################
# ubuntu Packaging                                                            #
###############################################################################

FROM base_ubuntu_PLATFORM_VERSION as pkg_TOOLCHAIN_NAME_TOOLCHAIN_BRANCH_ubuntu_PLATFORM_VERSION

# env
ENV INSTALL_PREFIX=/opt/TOOLCHAIN_NAME/TOOLCHAIN_VERSION

# copy install dir
COPY --from=build_TOOLCHAIN_NAME_TOOLCHAIN_BRANCH_ubuntu_PLATFORM_VERSION /opt/TOOLCHAIN_NAME /opt/TOOLCHAIN_NAME

# Copy control file
COPY data/control /tmp/
RUN export TODAY=`date "+%Y%m%d"` && \
    mkdir -p /tmp/TOOLCHAIN_NAME-TOOLCHAIN_VERSION-ubuntu-PLATFORM_VERSION-${TODAY}_arm64/DEBIAN && \
    mv /tmp/control /tmp/TOOLCHAIN_NAME-TOOLCHAIN_VERSION-ubuntu-PLATFORM_VERSION-${TODAY}_arm64/DEBIAN

# create deb file
RUN export TODAY=`date "+%Y%m%d"` && \
    cd /tmp && \
    mv -v /opt /tmp/TOOLCHAIN_NAME-TOOLCHAIN_VERSION-ubuntu-PLATFORM_VERSION-${TODAY}_arm64/ && \
    dpkg-deb --build TOOLCHAIN_NAME-TOOLCHAIN_VERSION-ubuntu-PLATFORM_VERSION-${TODAY}_arm64

# install the deb file
RUN export TODAY=`date "+%Y%m%d"` && \
    cd /tmp && \
    dpkg -i TOOLCHAIN_NAME-TOOLCHAIN_VERSION-ubuntu-PLATFORM_VERSION-${TODAY}_arm64.deb
